# site settings
title: WIA
subtitle: what is after
email: whatisaftersite@gmail.com
description: 🔴Digital artist | 🟠Illustrator | 🟡Graphic designer
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: https://whatisafter.github.io
author: ichone4
street_address: Downthe Rabbithole
city: Illustown
state: VS
zip_code: 2391
country: Neverland
phone: (555) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/whatisafter
  #GitLab:
  #Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram: https://www.instagram.com/whatisafter/
  #LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
  #Twitter: https://twitter.com/andrewbanchich
  #Facebook:
  #Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
